### PR TITLE
Add syntax highlighting for eval(, $[, S{, DL{, L{

### LINKED ISSUE #12: Need syntax highlighting for << >>, <PRIVATE PRIVATE>, eval(, $[, S{, DL{, L{
It does not highlight `<< ... >>`, `<PRIVATE ... PRIVATE>`, `eval(`, `$[`, `S{`, `DL{`, `L{`.

### PR DESCRIPTION
**Pull request by h0le**
Fixes #12

### CODE REVIEW

**Comment by rkoeninger** [comment]
@v0idNULL Want me to go ahead and release this, or do you want to include the other symbols mentioned in #12?

**Comment by h0le** [comment]
@rkoeninger I don't know how to code `<<` `<` in yaml and in format of .tmLanguage file.

**Comment by rkoeninger** [comment]
In the .tmLanguage file, it's xml, so `<`, `>` have to be escaped as `&lt;`, `&gt;` for the sake of xml.

I don't think those characters require any escaping for regex or yaml.

**Comment by rkoeninger** [comment]
@v0idNULL  Added the remaining symbols `<<`, `>>`, `<PRIVATE`, `PRIVATE>`, as well as `<`, `>`, `<=`, `>=`, `=`.

You have to phrase it `Fixes #12` for GitHub to automatically close the issue,

If you don't need anything else, I'll merge and release.

**Comment by h0le** [comment]
@rkoeninger  OK.

**Comment by rkoeninger** [comment]
Merged and released as v0.1.12

**Pull request merged**
